cors:
  originPatterns: http://localhost:3000,http://localhost:8080
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-lenght: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java_rest?useTimezone=true&serverTimezone=UTC
    username: root
    password: conape
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: false
    open-in-view: false
springdoc:
  pathsToMatch: /api/**/v1/**
  swagger-ui:
    use-root-path: true
